core = "7.x"
api = "2"

projects[entityreference][subdir] = "contrib"
projects[link][subdir] = "contrib"
projects[addressfield][subdir] = "contrib"
projects[date][subdir] = "contrib"
projects[field_placeholder][subdir] = "contrib"
projects[field_quick_required][subdir] = "contrib"
projects[field_collection][subdir] = "contrib"
projects[field_collection_tabs_widget][subdir] = "contrib"
projects[computed_field][subdir] = "contrib"
